### ISSUE TITLE
Doesn't install on Ubuntu 20.04

### ISSUE THREAD

**Issue by iPublicis** [ebruck/indicator-doom-cpu#5]
Issues with dependencies.

**Comment by rjzak** [comment]
I suspect it's this:
```
Traceback (most recent call last):
  File "/home/rjzak/Downloads/indicator-doom-cpu/indicator-doom-cpu", line 185, in <module>
    DOOMCPUStatusIcon().run()
  File "/home/rjzak/Downloads/indicator-doom-cpu/indicator-doom-cpu", line 171, in __init__
    AbstractDOOMCPUIndicator.__init__(self)
  File "/home/rjzak/Downloads/indicator-doom-cpu/indicator-doom-cpu", line 102, in __init__
    self.build_menu()
  File "/home/rjzak/Downloads/indicator-doom-cpu/indicator-doom-cpu", line 108, in build_menu
    self.menu = Gtk.Menu()
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python3/dist-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'Menu'
```

Installing `gir1.2-gmenu-3.0` and `libgnome-menu-3-0` didn't help.
OS: Pop_OS! 22.04
